### ISSUE TITLE
쿠폰 api path, 기타 기능 수정

### ISSUE THREAD

**Issue by Xylitol311** [zerobaseteam2/E-Commerce#107]
## Description

전체적인 쿠폰 기능 수정
- 쿠폰 기능 api path
- 테스트 용도로 임시로 만들었던 컨트롤러 삭제
- 쿠폰 목록 조회는 회원만 가능하도록 권한 설정
- 관리자가 특정 회원의 쿠폰 목록을 확인하는 기능 추가

## To-do

- [ ] api path 수정
- [ ] 컨트롤러 삭제
- [ ] 메서드 권한 설정
- [ ] 관리자 기능 추가
